
name: Testing workflow

on:
  push:
    paths: ['Makefile', '.github/workflows/**', '*.c', test_all.py]
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['Makefile', '.github/workflows/**', '*.c', test_all.py]
  workflow_dispatch:

jobs:
  macOS-latest-make:
    runs-on: macos-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update
          brew install llvm libomp

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pip setup
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build
        id: make_build
        run: |
          export PATH="/usr/local/opt/llvm/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          make compile

      - name: Run Tests
        run: |
          pytest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()  # Ensure artifacts are uploaded even if pytest fails
        with:
          name: upload_files_mac
          path: |
            test_outputs/
